[[ifaces]]
name = "eth0"
zone_type = "wan"
enable_in_boot = true

[[ifaces]]
name = "eth1"
zone_type = "lan"
enable_in_boot = true

[[ipconfigs]]
iface_name = "eth0"
enable = true

[ipconfigs.ip_model]
t = "dhcpclient"
default_router = true

[[nats]]
iface_name = "eth0"
enable = true

[[dhcpv4_services]]
iface_name = "eth1"
enable = true

[dhcpv4_services.config]
ip_range_start = "192.168.10.2"
ip_range_end = "192.168.10.254"
server_ip_addr = "192.168.10.1"
network_mask = 24

[[route_lans]]
iface_name = "eth1"
enable = true

[[route_wans]]
iface_name = "eth0"
enable = true

[[static_nat_mappings]]
enable = true
remark = "DHCPv4 Client Port"
lan_ipv4 = "0.0.0.0"
ipv4_l4_protocol = [17]
ipv6_l4_protocol = []

[[static_nat_mappings.mapping_pair_ports]]
wan_port = 68
lan_port = 68

[[static_nat_mappings]]
enable = true
remark = "DHCPv6 Client Port"
lan_ipv6 = "::"
ipv4_l4_protocol = []
ipv6_l4_protocol = [17]

[[static_nat_mappings.mapping_pair_ports]]
wan_port = 546
lan_port = 546

[[static_nat_mappings]]
enable = true
remark = "SSH Access"
lan_ipv4 = "0.0.0.0"
ipv4_l4_protocol = [6]
ipv6_l4_protocol = []

[[static_nat_mappings.mapping_pair_ports]]
wan_port = 22
lan_port = 22

[[static_nat_mappings.mapping_pair_ports]]
wan_port = 6443
lan_port = 6443
